import React, { CSSProperties } from 'react';
export interface IconProps {
    icon: any;
    spin?: boolean;
    className?: string;
    color?: string;
    fixedWidth?: boolean;
    size?: 'xs' | 'lg' | 'sm';
    style?: CSSProperties;
}
export declare const icons: {
    readonly checkActive: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly checkInactive: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly desc: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly asc: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly list: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly folder: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly folderCreate: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly folderOpen: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly smallThumbnail: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly largetThumbnail: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly angleRight: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly angleDown: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly download: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly upload: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly trash: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly directoryUp: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly fallbackIcon: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly symlink: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly hidden: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly loading: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly file: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly license: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly code: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly config: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly model: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly database: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly text: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly archive: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly csv: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly image: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly pdf: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly word: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly video: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly info: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly key: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly lock: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly music: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly flash: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly terminal: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly authors: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly adobe: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly git: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly linux: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly nodejs: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly php: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly python: import("@fortawesome/fontawesome-common-types").IconDefinition;
    readonly ubuntu: import("@fortawesome/fontawesome-common-types").IconDefinition;
};
export declare const Icon: React.FC<IconProps>;
